name: exitlive_transformers
description: Browser Config Transformer
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  logging: any
  barback: any
  dart_config: any
dev_dependencies:
  unittest: any
  mock: any

