name: html_config_injector
authors:
  - Erik Enomaa <e.enomaa@umiami.edu>
  - Matias Meno <matias.meno@exitlive.io>
homepage: https://github.com/exitlive/html-config-injector
description: Html Config Injector Transformer
version: 0.0.1
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  barback: ^0.15.2
  dart_config: ^0.5.0

